from pathlib import Path
import sys

MARK='CSM_NATIVE_NFE_WORKFLOW_3130'
if len(sys.argv)!=2:
    raise SystemExit('uso: patch_native_nfe_workflow_3130.py <pasta-web>')
web=Path(sys.argv[1])
app=web/'app.js'
if not app.is_file():
    raise SystemExit('app.js não encontrado')
s=app.read_text(encoding='utf-8')
if MARK in s:
    print('Frontend NF-e 3.13.0 já aplicado')
    raise SystemExit(0)
if 'CSM_NATIVE_FISCAL_CORE_3120' not in s:
    raise SystemExit('Aplique patch_native_fiscal_core_3120.py antes')

module=r'''
// CSM_NATIVE_NFE_WORKFLOW_3130 — consulta simples, certificados integrados, Ciência explícita e XML para G5.
(function(){
'use strict';
const API='http://127.0.0.1:47878';
const OVERLAY='csm-nfe-3130-overlay';
const STYLE='csm-nfe-3130-style';
function digits(v){return String(v||'').replace(/\D/g,'')}
function calcDv(base){if(!/^\d{43}$/.test(base))return -1;let sum=0,w=2;for(let i=42;i>=0;i--){sum+=Number(base[i])*w;w++;if(w>9)w=2}let d=11-(sum%11);return d===10||d===11?0:d}
function keyOf(v){const x=digits(v);if(x.length!==44)return'';return calcDv(x.slice(0,43))===Number(x[43])?x:''}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
async function request(path,body,method){const opt={method:method||'POST',headers:{'Content-Type':'application/json'}};if(body!==undefined)opt.body=JSON.stringify(body);const r=await fetch(API+path,opt);let data={};try{data=await r.json()}catch(_){data={message:await r.text().catch(()=> '')}}if(!r.ok)throw new Error(data?.message||`Falha local HTTP ${r.status}`);return data}
function injectStyle(){if(document.getElementById(STYLE))return;const s=document.createElement('style');s.id=STYLE;s.textContent=`
#${OVERLAY}{position:fixed;inset:0;z-index:2147483600;background:rgba(3,10,22,.76);backdrop-filter:blur(5px);display:flex;align-items:center;justify-content:center;padding:22px;font-family:Inter,Segoe UI,Arial,sans-serif}
.csm3130-card{width:min(760px,calc(100vw - 36px));max-height:calc(100vh - 44px);overflow:auto;background:linear-gradient(180deg,#101b2f,#0a1322);border:1px solid rgba(91,159,235,.28);border-radius:17px;box-shadow:0 28px 80px rgba(0,0,0,.55);color:#eef6ff}.csm3130-head{display:flex;justify-content:space-between;align-items:flex-start;padding:21px 23px 12px}.csm3130-title{font-size:19px;font-weight:800}.csm3130-sub{font-size:12px;color:#91a9c8;margin-top:5px}.csm3130-x{border:0;background:transparent;color:#a5bbd4;font-size:25px;cursor:pointer}.csm3130-body{padding:10px 23px 23px}.csm3130-label{display:block;color:#9db4d0;font-size:11px;font-weight:800;text-transform:uppercase;letter-spacing:.07em;margin:13px 0 7px}.csm3130-row{display:flex;gap:9px;align-items:center}.csm3130-input,.csm3130-select{width:100%;box-sizing:border-box;border:1px solid #315174;border-radius:10px;background:#07111f;color:#f2f7ff;padding:11px 12px;outline:none}.csm3130-input:focus,.csm3130-select:focus{border-color:#55a5ff;box-shadow:0 0 0 3px rgba(85,165,255,.13)}.csm3130-btn{border:1px solid #337fc9;border-radius:10px;background:#156dcc;color:white;padding:11px 15px;font-weight:750;cursor:pointer;white-space:nowrap}.csm3130-btn.secondary{background:#102541;border-color:#34506f;color:#d7e7fa}.csm3130-btn.ghost{background:transparent;border-color:#36516f;color:#bad0e8}.csm3130-btn.warn{background:#7d5310;border-color:#b98024}.csm3130-btn:disabled{opacity:.55;cursor:default}.csm3130-status{margin-top:14px;padding:11px 12px;border-radius:10px;background:#0d1a2b;color:#a9bed7;font-size:12px;line-height:1.45;min-height:18px}.csm3130-status.ok{border:1px solid rgba(58,186,112,.35);color:#9de4b8}.csm3130-status.err{border:1px solid rgba(235,91,91,.35);color:#ffaaaa}.csm3130-result{margin-top:12px;display:none;padding:13px;border:1px solid #263f5d;border-radius:11px;background:#0b1727}.csm3130-result.show{display:block}.csm3130-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:12px}.csm3130-manage{display:none;margin-top:15px;padding:14px;border:1px solid #283f5b;border-radius:11px;background:#0b1626}.csm3130-manage.show{display:block}.csm3130-cert-list{display:grid;gap:8px;margin-top:10px}.csm3130-cert{padding:10px;border:1px solid #29415f;border-radius:9px;background:#0c1a2d}.csm3130-cert strong{display:block;font-size:12px}.csm3130-cert small{color:#8199b6}.csm3130-hint{font-size:11px;color:#7690ae;margin-top:7px}.csm3130-manual{display:none;margin-top:10px;padding-top:10px;border-top:1px solid #253b55}.csm3130-manual.show{display:block}
body.light .csm3130-card{background:#f7fbff;color:#18334e;border-color:#c7d7e7}body.light .csm3130-input,body.light .csm3130-select{background:#fff;color:#18334e;border-color:#b8ccdf}body.light .csm3130-status,body.light .csm3130-result,body.light .csm3130-manage,body.light .csm3130-cert{background:#edf5fc;color:#36536f;border-color:#c8d9e8}
`;document.head.appendChild(s)}
function openModal(prefill=''){
 injectStyle();document.getElementById(OVERLAY)?.remove();
 const o=document.createElement('div');o.id=OVERLAY;o.innerHTML=`<div class="csm3130-card"><div class="csm3130-head"><div><div class="csm3130-title">Consultar NF-e</div><div class="csm3130-sub">Consulte pela chave. O CSM usa os Web Services oficiais e só salva arquivo quando você pedir.</div></div><button class="csm3130-x" type="button">×</button></div><div class="csm3130-body"><label class="csm3130-label">Chave de acesso</label><div class="csm3130-row"><input id="csm3130-key" class="csm3130-input" inputmode="numeric" placeholder="44 dígitos da chave de acesso"><button id="csm3130-go" class="csm3130-btn" type="button">Consultar</button></div><label class="csm3130-label">Empresa / certificado A1</label><div class="csm3130-row"><select id="csm3130-cert" class="csm3130-select"><option value="">Automático</option></select><button id="csm3130-manage-toggle" class="csm3130-btn secondary" type="button">Certificados</button></div><div class="csm3130-hint">Se o CSM já reconhecer o certificado da empresa, basta colar a chave e consultar.</div><div id="csm3130-status" class="csm3130-status">Pronto para consultar.</div><div id="csm3130-result" class="csm3130-result"></div><div id="csm3130-manage" class="csm3130-manage"><strong>Certificados digitais A1</strong><div class="csm3130-hint">Adicione a pasta onde ficam os PFX/P12. O padrão EMPRESA - SENHA.pfx é reconhecido localmente e a senha não é mostrada na interface.</div><div class="csm3130-row" style="margin-top:10px"><input id="csm3130-folder" class="csm3130-input" placeholder="Ex.: U:\\CERTIFICADOS ou \\\\servidor\\certificados"><button id="csm3130-add-folder" class="csm3130-btn secondary" type="button">Adicionar pasta</button></div><div class="csm3130-actions"><button id="csm3130-scan" class="csm3130-btn secondary" type="button">Procurar certificados</button><button id="csm3130-pick" class="csm3130-btn ghost" type="button">Selecionar A1 manualmente</button></div><div id="csm3130-cert-list" class="csm3130-cert-list"></div><div id="csm3130-manual" class="csm3130-manual"><div id="csm3130-picked" class="csm3130-hint"></div><div class="csm3130-row" style="margin-top:8px"><input id="csm3130-password" class="csm3130-input" type="password" autocomplete="new-password" placeholder="Senha do certificado"><button id="csm3130-validate" class="csm3130-btn secondary" type="button">Validar A1</button></div></div></div></div></div>`;
 document.body.appendChild(o);
 const q=id=>o.querySelector('#'+id),key=q('csm3130-key'),cert=q('csm3130-cert'),go=q('csm3130-go'),status=q('csm3130-status'),result=q('csm3130-result'),manage=q('csm3130-manage'),list=q('csm3130-cert-list'),manual=q('csm3130-manual'),picked=q('csm3130-picked'),password=q('csm3130-password');let pickedToken='';
 const setStatus=(m,k='')=>{status.textContent=m;status.className='csm3130-status '+k};
 const close=()=>o.remove();o.querySelector('.csm3130-x').onclick=close;o.addEventListener('mousedown',e=>{if(e.target===o)close()});
 async function loadCerts(scan=false){try{if(scan)await request('/fiscal/certificates/scan',{});const data=await request('/fiscal/certificates',undefined,'GET');const arr=Array.isArray(data?.certificates)?data.certificates:[];const current=cert.value;cert.innerHTML='<option value="">Automático</option>';for(const c of arr){if(!c?.cnpj)continue;const op=document.createElement('option');op.value=String(c.cnpj);op.textContent=`${c.empresa||c.cnpj}${c.expiry?' • vence '+c.expiry:''}`;cert.appendChild(op)}if([...cert.options].some(x=>x.value===current))cert.value=current;list.innerHTML=arr.length?'':'<div class="csm3130-hint">Nenhum certificado encontrado.</div>';for(const c of arr){const d=document.createElement('div');d.className='csm3130-cert';const days=Number(c.days_remaining||0);d.innerHTML=`<strong>${esc(c.empresa||c.file_name||'Certificado A1')}</strong><small>${esc(c.cnpj||'CNPJ não identificado')} • ${esc(c.status||'Pendente')}${c.expiry?' • vence '+esc(c.expiry):''}${days?' • '+days+' dias':''}</small>`;list.appendChild(d)}return arr}catch(e){list.innerHTML='<div class="csm3130-hint">'+esc(e.message)+'</div>';return[]}}
 function actionsFor(data,k){result.className='csm3130-result show';const st=esc(data?.status||'NF-e encontrada'),msg=esc(data?.message||data?.distribution_message||'Consulta concluída.');result.innerHTML=`<strong>${st}</strong><div class="csm3130-hint">${msg}</div><div class="csm3130-actions"></div>`;const a=result.querySelector('.csm3130-actions');if(data?.xml_available){const v=document.createElement('button');v.className='csm3130-btn';v.textContent='Visualizar NF-e';v.onclick=async()=>{try{await request('/fiscal/nfe/open-cached',{key:k});setStatus('Abrindo a NF-e no Visualizador…','ok')}catch(e){setStatus(e.message,'err')}};a.appendChild(v);const x=document.createElement('button');x.className='csm3130-btn secondary';x.textContent='Salvar XML';x.onclick=async()=>{try{const r=await request('/fiscal/nfe/export-xml',{key:k});if(!r.cancelled)setStatus('XML oficial salvo: '+(r.file_name||'arquivo XML'),'ok')}catch(e){setStatus(e.message,'err')}};a.appendChild(x);const p=document.createElement('button');p.className='csm3130-btn ghost';p.textContent='DANFE / PDF';p.onclick=async()=>{try{await request('/fiscal/nfe/open-cached',{key:k});setStatus('NF-e aberta. Use “Salvar PDF” na barra superior para gerar o DANFE/PDF.','ok')}catch(e){setStatus(e.message,'err')}};a.appendChild(p)}else if(data?.requires_manifestation){const m=document.createElement('button');m.className='csm3130-btn warn';m.textContent='Obter XML completo';m.onclick=()=>manifest(k,data);a.appendChild(m)}}
 async function manifest(k,data){const cnpj=String(data?.cnpj||cert.value||'').trim();if(!cnpj){setStatus('Selecione o certificado da empresa destinatária antes de registrar a Ciência.','err');manage.classList.add('show');return}const empresa=data?.empresa||'empresa selecionada';if(!window.confirm(`Para obter o XML completo será registrada Ciência da Operação (210210) em nome de ${empresa}. Esta é uma manifestação fiscal transmitida à SEFAZ. Deseja continuar?`))return;setStatus('Registrando Ciência da Operação e consultando o XML…','');try{const r=await request('/fiscal/nfe/manifestar',{key:k,cnpj,event:'210210'});if(r?.xml_available){setStatus('Ciência registrada e XML completo recebido.','ok');actionsFor({...r,status:'AUTORIZADA'},k)}else{setStatus(r?.message||'Ciência registrada. A Receita ainda não liberou o XML completo; tente consultar novamente mais tarde.','ok');actionsFor({...r,status:'CIÊNCIA REGISTRADA'},k)}}catch(e){setStatus(e.message,'err')}}
 async function consult(){const k=keyOf(key.value);if(!k){setStatus('A chave precisa ter 44 dígitos e DV válido.','err');return}go.disabled=true;result.className='csm3130-result';setStatus('Consultando a NF-e nos Web Services oficiais…','');try{const data=await request('/fiscal/nfe/consultar',{key:k,cnpj:String(cert.value||'')});if(data?.needs_certificate){setStatus(data.message||'Selecione o certificado da empresa para continuar.','err');manage.classList.add('show');await loadCerts();return}if(!data?.ok){setStatus(data?.message||'A consulta não pôde ser concluída.','err');return}const st=String(data.status||'').toUpperCase();if(data.xml_available)setStatus(`NF-e ${st}. XML oficial disponível no CSM.`,'ok');else if(data.requires_manifestation)setStatus(`NF-e ${st}. A Receita retornou apenas o resumo. Você pode registrar Ciência para solicitar o XML completo.`,'');else setStatus(`NF-e ${st}: ${data.message||'consulta concluída.'}`,st==='CANCELADA'||st==='DENEGADA'?'err':'ok');actionsFor(data,k)}catch(e){setStatus(e.message,'err')}finally{go.disabled=false}}
 go.onclick=consult;key.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();consult()}if(e.key==='Escape')close()});
 q('csm3130-manage-toggle').onclick=()=>manage.classList.toggle('show');q('csm3130-scan').onclick=async()=>{setStatus('Procurando certificados A1…','');await loadCerts(true);setStatus('Varredura de certificados concluída.','ok')};q('csm3130-add-folder').onclick=async()=>{const path=String(q('csm3130-folder').value||'').trim();if(!path){setStatus('Informe o caminho da pasta de certificados.','err');return}try{await request('/fiscal/certificate-folders/add',{path});q('csm3130-folder').value='';await loadCerts(true);setStatus('Pasta adicionada e certificados atualizados.','ok')}catch(e){setStatus(e.message,'err')}};
 q('csm3130-pick').onclick=async()=>{try{const r=await request('/fiscal/certificate/pick',{});if(r.cancelled)return;pickedToken=r.token||'';picked.textContent='Selecionado: '+(r.file_name||'certificado A1');manual.classList.add('show');password.value='';password.focus()}catch(e){setStatus(e.message,'err')}};q('csm3130-validate').onclick=async()=>{if(!pickedToken){setStatus('Selecione um certificado A1 primeiro.','err');return}try{const r=await request('/fiscal/certificate/validate',{token:pickedToken,password:password.value});password.value='';pickedToken='';manual.classList.remove('show');await loadCerts(true);setStatus(r?.message||'Certificado validado e protegido no Windows.','ok')}catch(e){password.value='';setStatus(e.message,'err')}};
 key.value=prefill||'';loadCerts();setTimeout(()=>{key.focus();key.select()},30)
}
function interceptClick(e){const b=e.target?.closest?.('[data-csm-native-lookup="1"]');if(!b)return;e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();openModal()}
document.addEventListener('click',interceptClick,true);
window.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&!e.altKey&&String(e.key).toLowerCase()==='l'){e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();openModal()}},true);
setTimeout(()=>{if(window.CSMNativeKeyLookup)window.CSMNativeKeyLookup.show=openModal},0);
window.CSMNFe3130={show:openModal,version:'3.13.0'};
})();
'''

s=s.rstrip()+"\n\n"+module.strip()+"\n"
for tok in (MARK,'Obter XML completo','/fiscal/nfe/manifestar','/fiscal/nfe/export-xml','/fiscal/certificate-folders/add','/fiscal/certificate/pick','Registrar Ciência'):
    if tok not in s: raise SystemExit('Frontend 3.13.0 incompleto: '+tok)
app.write_text(s,encoding='utf-8',newline='\n')
print('3.13.0: fluxo nativo NF-e + certificados + Ciência + XML aplicado ao frontend.')
