const fs=require('fs');
const appPath=process.env.CSM_APP_JS;
const cssPath=process.env.CSM_CSS;
if(!appPath||!cssPath)throw new Error('CSM_APP_JS/CSM_CSS não informados');
const app=fs.readFileSync(appPath,'utf8');
const css=fs.readFileSync(cssPath,'utf8');
function req(cond,msg){if(!cond)throw new Error(msg)}
req(app.includes('CSM_FOLDER_IMPORT_PROGRESS_V3'),'V3 ausente');
req(app.includes("fetch('http://127.0.0.1:47878/pick-folder'"),'picker separado ausente');
req(app.includes("fetch('http://127.0.0.1:47878/list-folder'"),'listagem separada ausente');
req(app.includes('window.pywebview.api.open_dropped_paths(paths)'),'Core _load_paths não é reutilizado via open_dropped_paths');
req(app.includes("document.body.classList.toggle('csm-folder-import-busy'"),'estado bloqueado ausente');
req(app.includes('stopImmediatePropagation()'),'atalhos não são bloqueados durante importação');
req(app.includes("typeof document.activeElement.blur==='function'"),'foco ativo não é removido durante importação');
const a=app.indexOf('async function openFolder(){');
const b=app.indexOf('\nfunction handleLoadResult',a);
req(a>=0&&b>a,'openFolder final não encontrado');
const fn=app.slice(a,b);
req(!fn.includes('window.pywebview.api.open_folder()'),'open_folder antigo ainda está no fluxo');
const pick=fn.indexOf('const picked=await csmPickFolderNative()');
const cancel=fn.indexOf("if(picked?.cancelled||!picked?.path)return;");
const show=fn.indexOf("csmFolderImportShow('Preparando a pasta selecionada...')");
const paint=fn.indexOf('await csmNextPaint();',show);
const load=fn.indexOf('window.pywebview.api.open_dropped_paths(paths)');
req(pick>=0&&cancel>pick&&show>cancel&&paint>show&&load>paint,'ordem picker → confirmação → modal → paint → processamento inválida');
req(!fn.includes('focusTimer')&&!fn.includes('fallbackTimer')&&!fn.includes("addEventListener('blur'"),'detecção frágil de foco voltou');
req(css.includes('CSM_FOLDER_IMPORT_PROGRESS_V3'),'CSS V3 ausente');
req(css.includes('position:fixed!important'),'overlay não é fixed');
req(css.includes('inset:0!important'),'overlay não ocupa a tela');
req(!css.includes('right:auto!important')&&!css.includes('bottom:auto!important'),'regressão: right/bottom auto encolhe o overlay');
req(css.includes('z-index:2147483647!important'),'overlay pode ficar atrás da interface');
req(css.includes('align-items:center!important')&&css.includes('justify-content:center!important'),'modal não está centralizado');
req(css.includes('.csm-folder-import-card'),'cartão central ausente');
req(css.includes('body.csm-folder-import-busy>*:not(#csmFolderImportProgress)'),'interface de fundo não é desabilitada');
req(css.includes('pointer-events:none!important;user-select:none!important'),'bloqueio real da interface ausente');
req(css.includes('.csm-folder-import-progress.show')&&css.includes('pointer-events:auto!important'),'overlay não bloqueia mouse');
console.log('OK: picker primeiro; overlay fullscreen central; fundo e atalhos bloqueados durante processamento.');
