const fs=require('fs');const {JSDOM}=require('jsdom');
const code=fs.readFileSync(__dirname+'/difal_st_module.js','utf8');const xml=fs.readFileSync(__dirname+'/difal_st_fixture.xml','utf8');
(async()=>{const dom=new JSDOM('<!doctype html><body><section class="content-panel"><div class="view-tabs"><button class="view-tab" data-view="fiscal">Fiscal</button></div><div id="fiscalView" class="view"></div></section></body>',{runScripts:'outside-only',pretendToBeVisual:true});const w=dom.window;
let active={document_id:'d1',model:'55',doc_type:'nfe'};w.state={activeId:'d1',activeView:'pdf'};w.activeDoc=()=>active;w.switchView=async v=>{w.state.activeView=v;w.document.querySelectorAll('.view').forEach(x=>x.classList.toggle('active',x.id===v+'View'))};w.activateDocument=async()=>{};w.showWelcome=()=>{};w.pywebview={api:{get_xml_text:async()=>({ok:true,xml})}};
w.eval(code);await new Promise(r=>w.setTimeout(r,20));const api=w.CSM_DIFAL_ST;if(!api)throw new Error('API DIFAL/ST ausente');const note=api.parseXml(xml);if(note.emitUF!=='PR'||note.destUF!=='SP'||note.items.length!==2)throw new Error('Leitura básica do XML falhou');
const cfg={purposeAll:'revenda',mva4:'',mva12:'',mvaOther:'',items:{1:{mode:'difal',purpose:'revenda',internalRate:18,mvaOverride:''},2:{mode:'difal',purpose:'revenda',internalRate:18,mvaOverride:''}}};let s=api.summarize(note,cfg);if(s.groups['12'].due!==60||s.groups['4'].due!==70||s.totalDifal!==130)throw new Error('DIFAL revenda incorreto '+JSON.stringify(s));
cfg.items[1].purpose='uso';cfg.items[2].purpose='uso';s=api.summarize(note,cfg);if(s.groups['12'].due!==66||s.groups['4'].due!==77||s.totalDifal!==143)throw new Error('DIFAL uso/consumo com IPI incorreto '+JSON.stringify(s));
cfg.items[1].mode='st';cfg.mva12='50';s=api.summarize(note,cfg);if(s.st.due!==177||s.groups['12'].count!==0||s.groups['4'].due!==77)throw new Error('ICMS ST/MVA ou exclusão do DIFAL incorreta '+JSON.stringify(s));
const btn=w.document.querySelector('[data-view="difalst"]');if(!btn)throw new Error('Aba DIFAL/ST não montou');btn.click();await new Promise(r=>w.setTimeout(r,40));const view=w.document.getElementById('difalstView');if(!view.textContent.includes('Alíquota interestadual 12%')||!view.textContent.includes('Alíquota interestadual 4%')||!view.textContent.includes('Calcular como ICMS ST'))throw new Error('UI DIFAL/ST incompleta');dom.window.close();console.log('OK - DIFAL 12/4, IPI uso/consumo, revenda e ICMS ST com MVA validados.');})().catch(e=>{console.error(e);process.exit(1)});
