const $=s=>document.querySelector(s);let docs=[],active=null,activeOp=null,opTimer=null;
const money=v=>{const n=Number(v||0);return n.toLocaleString('pt-BR',{style:'currency',currency:'BRL'})};
async function refresh(q=''){docs=await pywebview.api.documents(q);$('#stats').textContent=`${docs.length} documento(s) exibido(s)`;$('#list').innerHTML=docs.map((d,i)=>`<div class="row" data-i="${i}"><div class="top"><strong>${d.doc_type||'XML'} ${d.number||''}</strong><span>${money(d.total_value)}</span></div><small>${d.emitter_name||d.emitter_cnpj||'Sem emitente'}</small><small>${d.issue_date||''} • Série ${d.series||'-'}</small></div>`).join('');[...document.querySelectorAll('.row')].forEach(r=>r.onclick=()=>selectDoc(Number(r.dataset.i)))}
async function selectDoc(i){active=docs[i];document.querySelectorAll('.row').forEach((r,j)=>r.classList.toggle('active',j===i));$('#empty').classList.add('hidden');$('#doc').classList.remove('hidden');$('#docTitle').textContent=`${active.doc_type||'XML'} ${active.number||''}`;$('#docMeta').textContent=`${active.emitter_name||active.emitter_cnpj||''} • Série ${active.series||'-'} • ${active.issue_date||''}`;$('#docValue').textContent=money(active.total_value);try{XmlViewer.render(await pywebview.api.read_xml(active.path))}catch(e){$('#xmlCode').textContent=String(e)}}
function showOp(o){$('#operation').classList.remove('hidden');$('#opTitle').textContent=o.title||'Processando';$('#opMessage').textContent=(o.message||'')+(o.current?` — ${o.current}`:'');$('#opCount').textContent=o.total?`${o.processed||0} / ${o.total}`:'';$('#opBar').style.width=o.total?`${Math.min(100,(o.processed||0)*100/o.total)}%`:'8%';$('#cancelBtn').style.display=o.status==='running'?'':'none'}
async function watch(id){activeOp=id;clearInterval(opTimer);opTimer=setInterval(async()=>{const o=await pywebview.api.operation(id);if(!o||!o.id)return;showOp(o);if(o.status!=='running'){clearInterval(opTimer);setTimeout(()=>$('#operation').classList.add('hidden'),1600);if(o.kind==='import')refresh($('#globalSearch').value)}},120)}
$('#folderBtn').onclick=async()=>{const f=await pywebview.api.choose_folder();if(!f)return;const id=await pywebview.api.start_import(f);if(id)watch(id)};
$('#pdfBtn').onclick=async()=>{const files=await pywebview.api.choose_pdfs();if(!files.length)return;const id=await pywebview.api.start_pdf_merge(files);if(id)watch(id)};
$('#cancelBtn').onclick=()=>activeOp&&pywebview.api.cancel_operation(activeOp);let st;$('#globalSearch').oninput=e=>{clearTimeout(st);st=setTimeout(()=>refresh(e.target.value),180)};
window.addEventListener('pywebviewready',()=>{XmlViewer.bind();refresh()});
