const XmlViewer=(()=>{let raw='',pretty='',hits=[],current=-1;const fiscal=new Set(['vBC','pICMS','vICMS','vBCST','pICMSST','vICMSST','vFCP','vFCPST','vIPI','pIPI','vPIS','vCOFINS','vNF','vProd','vDesc','vFrete','vSeg','vOutro','vTotTrib','CFOP','CST','CSOSN','NCM','CEST','CNPJ','CPF','chNFe','chCTe','mod','serie','nNF','nItem']);const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function format(xml){try{const d=new DOMParser().parseFromString(xml,'application/xml');if(d.querySelector('parsererror'))return xml;const out=[];function walk(n,z){const p='  '.repeat(z);if(n.nodeType===1){let a='';for(const x of n.attributes)a+=' '+x.name+'="'+x.value+'"';const k=[...n.childNodes];if(!k.length){out.push(p+'<'+n.nodeName+a+'/>');return}const text=k.every(x=>x.nodeType===3||x.nodeType===4)&&k.map(x=>x.nodeValue||'').join('').trim().length<180;if(text){out.push(p+'<'+n.nodeName+a+'>'+k.map(x=>x.nodeValue||'').join('').trim()+'</'+n.nodeName+'>');return}out.push(p+'<'+n.nodeName+a+'>');k.forEach(x=>walk(x,z+1));out.push(p+'</'+n.nodeName+'>')}else if(n.nodeType===3){const t=(n.nodeValue||'').trim();if(t)out.push(p+t)}}walk(d.documentElement,0);return out.join('\n')}catch{return xml}}
function tag(t){const m=t.match(/^<\/?\s*([^\s/>]+)([\s\S]*?)(\/?)>$/);if(!m)return esc(t);const name=m[1],close=/^<\//.test(t),self=m[3]==='/';let h='&lt;'+(close?'/':'')+'<span class="x-tag '+(fiscal.has(name)?'x-fiscal':'')+'">'+esc(name)+'</span>';const rest=m[2]||'',re=/([^\s=]+)(\s*=\s*)(["'])([\s\S]*?)\3/g;let p=0,x;while((x=re.exec(rest))){h+=esc(rest.slice(p,x.index))+' <span class="x-attr">'+esc(x[1])+'</span>'+esc(x[2])+'<span class="x-value">'+esc(x[3]+x[4]+x[3])+'</span>';p=re.lastIndex}return h+esc(rest.slice(p))+(self?'/':'')+'&gt;'}
function highlight(xml){pretty=format(xml);let o='',p=0,cur='',re=/<[^>]+>/g,m;while((m=re.exec(pretty))){if(m.index>p)o+='<span class="x-text '+(cur?'x-fiscal':'')+'">'+esc(pretty.slice(p,m.index))+'</span>';const tm=m[0].match(/^<\/?\s*([^\s/>]+)/),close=/^<\//.test(m[0]),self=/\/>$/.test(m[0]);o+=tag(m[0]);if(tm){const n=tm[1];if(close&&cur===n)cur='';else if(!close&&!self&&fiscal.has(n))cur=n}p=re.lastIndex}if(p<pretty.length)o+='<span class="x-text '+(cur?'x-fiscal':'')+'">'+esc(pretty.slice(p))+'</span>';return o}
function clear(code){for(const m of [...code.querySelectorAll('mark.hit')]){const p=m.parentNode;p.replaceChild(document.createTextNode(m.textContent||''),m);p.normalize()}}
function find(code,q){clear(code);hits=[];current=-1;q=(q||'').trim().toLowerCase();if(!q){document.getElementById('xmlCount').textContent='0';return}const w=document.createTreeWalker(code,NodeFilter.SHOW_TEXT),nodes=[];while(w.nextNode())nodes.push(w.currentNode);for(const original of nodes){let n=original;while(n&&n.nodeType===3){const i=(n.nodeValue||'').toLowerCase().indexOf(q);if(i<0)break;let mm=n;if(i)mm=n.splitText(i);const tail=mm.splitText(q.length),mark=document.createElement('mark');mark.className='hit';mm.parentNode.replaceChild(mark,mm);mark.appendChild(mm);hits.push(mark);n=tail}}if(hits.length)go(0);else document.getElementById('xmlCount').textContent='0 / 0'}
function go(i){if(!hits.length)return;hits.forEach(x=>x.classList.remove('current'));current=(i+hits.length)%hits.length;hits[current].classList.add('current');hits[current].scrollIntoView({block:'center'});document.getElementById('xmlCount').textContent=(current+1)+' / '+hits.length}
function render(xml){raw=xml||'';const code=document.getElementById('xmlCode');code.innerHTML=highlight(raw);document.getElementById('xmlSearch').value='';document.getElementById('xmlCount').textContent='0';hits=[];current=-1}
function bind(){const code=document.getElementById('xmlCode'),input=document.getElementById('xmlSearch');input.addEventListener('input',()=>find(code,input.value));input.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();if(hits.length)go(current+(e.shiftKey?-1:1))}});document.getElementById('xmlPrev').onclick=()=>go(current-1);document.getElementById('xmlNext').onclick=()=>go(current+1);document.getElementById('xmlCopy').onclick=()=>navigator.clipboard.writeText(pretty||raw)}return{bind,render}})();
